version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: qrdb
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://devuser:devpass@postgres:5432/qrdb
    ports:
      - "3001:3001"
    volumes:
      - ./data:/data      # SQLite data gerekmez, ancak ortak volume örneği
      - ./backend:/app         # KODLARI MOUNT ET


  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    ports:
      - "3000:3000"
    environment:
      VITE_API_BASE_URL: http://localhost:3001/api